version: "3.9"
services:
  postgres:
    container_name: edu-demo-db-postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
      
  pgadmin:
    container_name: pgadmin-client
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"