version: "3.9"
services:
  postgres:
    container_name: edu-demo-db-postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"